name: Nicolas Fortin
description: Experiment. Inovate. Go further.
meta_description: "Nicolas Fortin. Blog Web Developper"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'zallek.gitgub.io'
google_analytics: 'UA-68695708-1'
disqus: true
disqus_shortname: 'zallek'

nav:
    -
        title: Home
        id: home
        url: ""
    -
        title: Bookmarks
        id: bookmarks
        url: bookmarks/
    -
        title: About
        id: about
        url: about/

# Details for the RSS feed generator
url:            'https://zallek.gitgub.io'
author:         'Nicolas Fortin'
authorTwitter:  'nicolas_for'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
